$(document).ready(function () {
    $('#errorMsg').hide();
    $('#fname, #lname').on('input', function () {
       
        var firstName = $('#fname').val().toLowerCase();
        var lastName = $('#lname').val().toLowerCase();
        
        var lecturerCode = (firstName + lastName.substring(0, 2)).toLowerCase() + '@lecnibm';

      
        $('#lcode').val(lecturerCode);
        function generatePassword(lecturerCode) {
            return 'lec' + lecturerCode;
        }
        
     
        $('#category').change(function () {
            if ($(this).val() !== '') {
                $(this).removeClass('border-danger');
                $('#errorMsg').hide();
            }
        });
        
        var autoGeneratedPassword = generatePassword(lecturerCode);
            $('#pass').val(autoGeneratedPassword);

        var autoGeneratedPassword = generatePassword(lecturerCode);
            $('#repass').val(autoGeneratedPassword);

            $('#submit').click(function () {
                var firstName = $('#fname').val().trim();
                var lastName = $('#lname').val().trim();
                var lecturerCode = $('#lcode').val();
                var category = $('#category').val();
                var password = $('#pass').val();
                var rePassword = $('#repass').val();
            
                $('#errorMsg').hide();
                $('.form-control').removeClass('border-danger');
            
                if (firstName === '' || lastName === '') {
                    $('#errorMsg').text('First name and last name should not be empty.').show();
                    return false;
                }
            
                if (/\s/.test(firstName) || /\s/.test(lastName)) {
                    $('#errorMsg').text('First name and last name should not contain spaces.').show();
                    return false;
                }
            
                if (category === '') {
                    $('#category').addClass('border-danger');
                    $('#errorMsg').text('Please select the course.').show();
                    return false;
                }
            
               
            
                if (!password.includes('lec') || !password.includes(lecturerCode)) {
                    $('#errorMsg').text('Auto-generated password should contain "lec" and the lecturer code.').show();
                    $('#pass').addClass('border-danger');
                    return false;
                }
            
                if (password !== rePassword) {
                    $('#errorMsg').text('Passwords do not match.').show();
                    $('#repass').addClass('border-danger');
                    return false;
                }
            
                // Perform other actions if validation is successful
                downloadTextFile(firstName + '_' + lastName + '_details.txt', 'Lecturer Code: ' + lecturerCode + '\nPassword: ' + password);
            
                return true;
            });
            
            
            function downloadTextFile(filename, text) {
                var blob = new Blob([text], { type: 'text/plain' });
                var a = document.createElement('a');
                a.href = URL.createObjectURL(blob);
                a.download = filename;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
            }

            $('#clear').click(function () {
                $('#errorMsg').hide();
                $('.form-control').removeClass('border-danger');
                $('form')[0].reset();  // Reset the form fields
            });

        $('#back').click(function () {
            // Implement your back button logic here
        });

    });
});